### ISSUE TITLE
Test failre on debian sid

### ISSUE THREAD

**Issue by avalentino** [pytroll/mipp#13]
```
$ python2.7 -m unittest discover -v tests
['~/debian/git/mipp', '~/debian/git/mipp/tests', '', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
test_config_parser (test_misc.Test) ... ok
test_tsx (test_xsar.Test) ... ok
test_decompress (test_xrit.Test)
Test decompressing MSG SEVIRI data on the fly with xRITDecompress ... /home/antonio/debian/git/mipp/tests/test_xrit.py:227: UserWarning: Environment variable XRIT_DECOMPRESS_PATH not set. Not possible to test decompression on the fly!
  warn(message)
ok
test_goes (test_xrit.Test) ... ok
test_hrv (test_xrit.Test) ... FAIL
test_hrv2 (test_xrit.Test) ... FAIL
test_met7 (test_xrit.Test) ... ok
test_msg (test_xrit.Test) ... FAIL
test_msg2 (test_xrit.Test) ... ok
test_mtsat (test_xrit.Test) ... ok

======================================================================
FAIL: test_hrv (test_xrit.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/debian/git/mipp/tests/test_xrit.py", line 195, in test_hrv
    self.assertTrue(compare_mda(mda, mdac), msg='MSG-HRV metadata differ')
AssertionError: MSG-HRV metadata differ

======================================================================
FAIL: test_hrv2 (test_xrit.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/debian/git/mipp/tests/test_xrit.py", line 214, in test_hrv2
    self.assertTrue(compare_mda(mda, mdac), msg='MSG-HRV metadata differ')
AssertionError: MSG-HRV metadata differ

======================================================================
FAIL: test_msg (test_xrit.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/debian/git/mipp/tests/test_xrit.py", line 157, in test_msg
    self.assertTrue(compare_mda(mda, mdac), msg='MSG metadata differ')
AssertionError: MSG metadata differ

----------------------------------------------------------------------
Ran 10 tests in 0.768s

FAILED (failures=3)
```

**Comment by avalentino** [comment]
Is there some progress on this?

**Comment by mraspaud** [comment]
@avalentino sorry for the late answer. I've just looked at this, and it seems there is a 1.5km offset in the area extent. I suspect the eumetsat planned geolocation fix and the mipp implementation of that might be screwing the tests.

But actually, mipp isn't really developed actively anymore. Can you consider switching to satpy, or do you really need mipp ?

**Comment by avalentino** [comment]
Yes @mraspaud, if mipp is no longer actively developed I agree that switching to satpy i the best option.
Anyway some of the reader for SAR data are not available in satpy, it is a pity.
Are there plans to improve that?

**Comment by mraspaud** [comment]
@avalentino Indeed, we haven't ported all the sar readers to satpy, but that would be very nice to have. We might not have the time/need to do it ourselves atm, but PRs are more than welcome!
