### ISSUE TITLE
Test failure on debian

### ISSUE THREAD

**Issue by avalentino** [pytroll/mipp#8]
I'm trying to prepare the debian package for mipp 0.10.0.

I have 2 failures when I run the test suite:

```
$ ./testit 
/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing 'v0.10.0' to '0.10.0'
  normalized_version,
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/mipp
copying mipp/version.py -> build/lib.linux-x86_64-2.7/mipp
copying mipp/mda.py -> build/lib.linux-x86_64-2.7/mipp
copying mipp/log.py -> build/lib.linux-x86_64-2.7/mipp
copying mipp/read_geotiff.py -> build/lib.linux-x86_64-2.7/mipp
copying mipp/cfg.py -> build/lib.linux-x86_64-2.7/mipp
copying mipp/__init__.py -> build/lib.linux-x86_64-2.7/mipp
creating build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/_xrit.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/mda.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/SGS.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/MTP.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/H8.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/GOMS.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/bin_reader.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/MSG.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/convert.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/sat.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/__init__.py -> build/lib.linux-x86_64-2.7/mipp/xrit
copying mipp/xrit/loader.py -> build/lib.linux-x86_64-2.7/mipp/xrit
creating build/lib.linux-x86_64-2.7/mipp/xsar
copying mipp/xsar/TSX.py -> build/lib.linux-x86_64-2.7/mipp/xsar
copying mipp/xsar/mda.py -> build/lib.linux-x86_64-2.7/mipp/xsar
copying mipp/xsar/S1A.py -> build/lib.linux-x86_64-2.7/mipp/xsar
copying mipp/xsar/CSK.py -> build/lib.linux-x86_64-2.7/mipp/xsar
copying mipp/xsar/RS2.py -> build/lib.linux-x86_64-2.7/mipp/xsar
copying mipp/xsar/sat.py -> build/lib.linux-x86_64-2.7/mipp/xsar
copying mipp/xsar/__init__.py -> build/lib.linux-x86_64-2.7/mipp/xsar
nosetests  -w tests
./home/antonio/debian/git/mipp/tests/test_xrit.py:227: UserWarning: Environment variable XRIT_DECOMPRESS_PATH not set. Not possible to test decompression on the fly!
  warn(message)
..FF./home/antonio/debian/git/mipp/mipp/xrit/loader.py:124: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if area_extent == None:
....
======================================================================
FAIL: test_hrv (test_xrit.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/mipp/tests/test_xrit.py", line 195, in test_hrv
    self.assertTrue(compare_mda(mda, mdac), msg='MSG-HRV metadata differ')
AssertionError: MSG-HRV metadata differ
-------------------- >> begin captured logging << --------------------
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-_________-PRO______-201010111400-__
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-_________-EPI______-201010111400-__
mipp/xrit/MSG: INFO: Using numexpr for fast numpy evaluation
mipp/xrit/MSG: DEBUG: msg2 09
mipp: INFO: Data size: 11136x11136 pixels, 155013120 bytes, 10 bits per pixel
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-HRV______-000012___-201010111400-__
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-HRV______-000013___-201010111400-__
mipp: DEBUG: slice2extent: size 1000, 600
mipp: DEBUG: slice2extent: computed extent -499567.11, -200526.94, 500567.24, 399553.67
mipp: DEBUG: slice2extent: computed size 1000, 600
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_hrv2 (test_xrit.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/mipp/tests/test_xrit.py", line 214, in test_hrv2
    self.assertTrue(compare_mda(mda, mdac), msg='MSG-HRV metadata differ')
AssertionError: MSG-HRV metadata differ
-------------------- >> begin captured logging << --------------------
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-_________-PRO______-201011091200-__
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-_________-EPI______-201011091200-__
mipp/xrit/MSG: INFO: Using numexpr for fast numpy evaluation
mipp/xrit/MSG: DEBUG: msg2 09
mipp: INFO: Data size: 11136x11136 pixels, 155013120 bytes, 10 bits per pixel
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-HRV______-000018___-201011091200-__
mipp: INFO: Read /home/antonio/debian/git/mipp/tests/data/H-000-MSG2__-MSG2________-HRV______-000018___-201011091200-__
mipp: DEBUG: slice2extent: size 8998, 450
mipp: DEBUG: slice2extent: computed extent -4820147.49, 2331813.23, 4179061.38, 2781873.69
mipp: DEBUG: slice2extent: computed size 8998, 450
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 10 tests in 0.680s

FAILED (failures=2)
```

Can you please provide some hint?

**Comment by avalentino** [comment]
Any news on this?

**Comment by mraspaud** [comment]
@avalentino Hi, sorry, I'm not back to work yet, so I didn't look at this. I'll be back next week, but I think that commit 42434f0af33a7575740f3092f63a1d903bf30685 broke the build. If that's the case, it's just a matter of adjusting the tests to expect the right values. @loerum are you working this week to check that ?

**Comment by loerum** [comment]
Hi Antonio and Martin,

The last checkin to the pre-master branch should fix the problem.

Best Regards, Lars

**Comment by avalentino** [comment]
Thanks @loerum
I can confirm it works
